In [1]:
# Import all needed libraries
import numpy as np
import pandas as pd

### Reading the data

In [2]:
data=pd.read_csv('Movie+Assignment+Data.csv')
data.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

### Inspect the data Frame

In [3]:
print(data.shape)
print(data.info())

(5043, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB
None

### Cleaning the data

In [4]:
# Check the null values
print(data.isnull().sum())

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [5]:
### Write your code for column-wise null percentages here
round(data.isnull().sum() *100/len(data),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

In [6]:
## So many of the columns in this dataframe are not required. It advised to drop columns
data=data.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],axis='columns')
data

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [7]:
#  Drop unecessary rows using columns with high Null percentages
f=round(data.isnull().sum() *100/len(data),2)
h=f.values
g=np.where(h>5)
name=f.index
for i in g:
    print(name[i])
    data=data.dropna(subset=name[i])
print(data.head())

Index(['gross', 'budget'], dtype='object')
       director_name  num_critic_for_reviews        gross  \
0      James Cameron                   723.0  760505847.0
1     Gore Verbinski                   302.0  309404152.0
2         Sam Mendes                   602.0  200074175.0
3  Christopher Nolan                   813.0  448130642.0
5     Andrew Stanton                   462.0   73058679.0

                            genres     actor_1_name  \
0  Action|Adventure|Fantasy|Sci-Fi      CCH Pounder
1         Action|Adventure|Fantasy      Johnny Depp
2        Action|Adventure|Thriller  Christoph Waltz
3                  Action|Thriller        Tom Hardy
5          Action|Adventure|Sci-Fi     Daryl Sabara

                                 movie_title  num_voted_users  \
0                                    Avatar            886204
1  Pirates of the Caribbean: At World's End            471220
2                                   Spectre            275868
3                     The Dark Knight Rises           1144337
5                               John Carter            212204

   num_user_for_reviews language       budget  title_year  imdb_score  \
0                3054.0  English  237000000.0      2009.0         7.9
1                1238.0  English  300000000.0      2007.0         7.1
2                 994.0  English  245000000.0      2015.0         6.8
3                2701.0  English  250000000.0      2012.0         8.5
5                 738.0  English  263700000.0      2012.0         6.6

   movie_facebook_likes
0                 33000
1                     0
2                 85000
3                164000
5                 24000

In [8]:
## Now again check the null percentage
round(data.isnull().sum() *100/len(data),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

In [9]:
# You can see we have some nan values in language columns. We can fill this value with English
data['language']=data['language'].fillna('English')
print(round(data.isnull().sum()*100/len(data),2))

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

<ipython-input-9-c94ab328185e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['language']=data['language'].fillna('English')

### Data Analysis

In [10]:
# Find the movies with highest profit
Profit=data['gross']-data['budget']
data['Profit']=Profit

<ipython-input-10-362e38db6e2f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Profit']=Profit

In [11]:
# Write your code for sorting the dataframe her
data.sort_values(by='Profit',ascending=False)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,2.370000e+08,2009.0,7.9,33000,5.235058e+08
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,1.500000e+08,2015.0,7.0,150000,5.021773e+08
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,2.000000e+08,1997.0,7.7,26000,4.586723e+08
3024,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,1.100000e+07,1977.0,8.7,33000,4.499357e+08
3080,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,1.050000e+07,1982.0,7.9,34000,4.244495e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,410388.0,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2.127520e+09,2004.0,6.9,973,-2.127110e+09
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,-2.397702e+09
3005,Lajos Koltai,73.0,195888.0,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2.500000e+09,2005.0,7.1,607,-2.499804e+09
3859,Chan-wook Park,202.0,211667.0,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4.200000e+09,2005.0,7.7,4000,-4.199788e+09
2988,Joon-ho Bong,363.0,2201412.0,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,1.221550e+10,2006.0,7.0,7000,-1.221330e+10

In [12]:
# Top 10 movies highest gross
top10=data.sort_values(by='Profit',ascending=False).head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000,502177271.0
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,458672302.0
3024,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11000000.0,1977.0,8.7,33000,449935665.0
3080,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10500000.0,1982.0,7.9,34000,424449459.0
794,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
17,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,403279547.0
509,Roger Allers,186.0,422783777.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45000000.0,1994.0,8.5,17000,377783777.0
240,George Lucas,320.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115000000.0,1999.0,6.5,13000,359544677.0
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,348316061.0

In [13]:
# in above top10 dataset you can see we have some duplicate values. Next task is to remove dublicate
data.drop_duplicates()
data.head(10)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,9404152.0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,-44925825.0
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,198130642.0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000,-190641321.0
6,Sam Raimi,392.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258000000.0,2007.0,6.2,0,78530303.0
7,Nathan Greno,324.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260000000.0,2010.0,7.8,29000,-59192738.0
8,Joss Whedon,635.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250000000.0,2015.0,7.5,118000,208991599.0
9,David Yates,375.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250000000.0,2009.0,7.5,10000,51956980.0
10,Zack Snyder,673.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250000000.0,2016.0,6.9,197000,80249062.0

In [14]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_top_250=data[data['num_voted_users']>25000]
IMDb_top_250=IMDb_top_250.sort_values(by='imdb_score',ascending=False).head(250)
IMDb_top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,3341469.0
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,128821952.0
2837,Francis Ford Coppola,149.0,57300000.0,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13000000.0,1974.0,9.0,14000,44300000.0
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,348316061.0
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1200000.0,1966.0,8.9,20000,4900000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,Paul Thomas Anderson,153.0,26384919.0,Drama,Don Cheadle,Boogie Nights,189032,560.0,English,15000000.0,1997.0,7.9,0,11384919.0
706,Quentin Tarantino,596.0,54116191.0,Crime|Drama|Mystery|Thriller|Western,Craig Stark,The Hateful Eight,272839,1018.0,English,44000000.0,2015.0,7.9,114000,10116191.0
2487,George Cukor,82.0,72000000.0,Drama|Family|Musical|Romance,Jeremy Brett,My Fair Lady,66959,258.0,English,17000000.0,1964.0,7.9,0,55000000.0
716,Doug Liman,249.0,121468960.0,Action|Mystery|Thriller,Matt Damon,The Bourne Identity,407601,849.0,English,60000000.0,2002.0,7.9,0,61468960.0
2605,Ang Lee,287.0,128067808.0,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15000000.0,2000.0,7.9,0,113067808.0

In [15]:
## Top foreign language movies
topFL=IMDb_top_250[IMDb_top_250['language']!='English']
topFL.head(20)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e+06,1966.0,8.9,20000,4.900000e+06
4747,Akira Kurosawa,153.0,269061.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e+06,1954.0,8.7,11000,-1.730939e+06
4029,Fernando Meirelles,214.0,7563397.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e+06,2002.0,8.7,28000,4.263397e+06
2373,Hayao Miyazaki,246.0,10049886.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e+07,2001.0,8.6,28000,-8.950114e+06
4259,Florian Henckel von Donnersmarck,215.0,11284657.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e+06,2006.0,8.5,39000,9.284657e+06
4921,Majid Majidi,46.0,925402.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e+05,1997.0,8.5,0,7.454020e+05
1298,Jean-Pierre Jeunet,242.0,33201661.0,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e+07,2001.0,8.4,39000,-4.379834e+07
1329,S.S. Rajamouli,44.0,6498000.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e+07,2015.0,8.4,21000,-1.152815e+07
4659,Asghar Farhadi,354.0,7098492.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e+05,2011.0,8.4,48000,6.598492e+06
2970,Wolfgang Petersen,96.0,11433134.0,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e+07,1981.0,8.4,11000,-2.566866e+06
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,11000,-2.397702e+09
4105,Chan-wook Park,305.0,2181290.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e+06,2003.0,8.4,43000,-8.187100e+05
4033,Thomas Vinterberg,349.0,610968.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e+06,2012.0,8.3,60000,-3.189032e+06
2829,Oliver Hirschbiegel,192.0,5501940.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e+07,2004.0,8.3,14000,-7.998060e+06
2734,Fritz Lang,260.0,26435.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e+06,1927.0,8.3,12000,-5.973565e+06
3550,Denis Villeneuve,226.0,6857096.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e+06,2010.0,8.2,37000,5.709600e+04
4000,Juan José Campanella,262.0,20167424.0,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e+06,2009.0,8.2,33000,1.816742e+07
2047,Hayao Miyazaki,212.0,4710455.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e+07,2004.0,8.2,13000,-1.928954e+07
2551,Guillermo del Toro,406.0,37623143.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e+07,2006.0,8.2,27000,2.412314e+07
4461,Thomas Vinterberg,98.0,1647780.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e+06,1998.0,8.1,5000,3.477800e+05

In [16]:
# Write your code for extracting the top 10 directors here
top10dir=data.groupby('director_name').imdb_score.mean().sort_values(ascending=False).head(10)
top10dir

director_name
Tony Kaye                8.600000
Charles Chaplin          8.600000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000
Name: imdb_score, dtype: float64

In [17]:
##Find popular genres
genres=data['genres'].str.split("|",n=-1, expand=True)
data['genre_1']=genres[0]
data['genre_2']=genres[1]
data.head(4)

<ipython-input-17-50f7e298252c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['genre_1']=genres[0]
<ipython-input-17-50f7e298252c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['genre_2']=genres[1]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,523505847.0,Action,Adventure
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,9404152.0,Action,Adventure
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,-44925825.0,Action,Adventure
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,198130642.0,Action,Thriller

In [18]:
#Most popular combo of genres
popgen=data.groupby(['genre_1','genre_2']).gross.mean().sort_values(ascending=False).head(5)
popgen

genre_1    genre_2
Family     Sci-Fi       4.349495e+08
Adventure  Sci-Fi       2.286278e+08
           Animation    1.169985e+08
           Family       1.165208e+08
Action     Adventure    1.103825e+08
Name: gross, dtype: float64

In [19]:
top_actor=data.actor_1_name.value_counts().sort_values(ascending=False).head(5)
top_actor

Robert De Niro       42
Johnny Depp          39
J.K. Simmons         31
Nicolas Cage         31
Denzel Washington    30
Name: actor_1_name, dtype: int64

In [20]:
# now let's find the total movies each actor have done
#1.) Robert De Niro
Robert_De_Niro=data[data['actor_1_name']=='Robert De Niro']
Robert_De_Niro
#2.) Johnny Depp
Johnny_Depp=data[data['actor_1_name']=='Johnny Depp']
Johnny_Depp
#3.) Nicolas Cage
Nicolas_Cage=data[data['actor_1_name']=='Nicolas Cage']
Nicolas_Cage

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
104,Jon Turteltaub,235.0,63143812.0,Action|Adventure|Family|Fantasy,Nicolas Cage,The Sorcerer's Apprentice,124185,238.0,English,150000000.0,2010.0,6.1,11000,-86856188.0,Action,Adventure
224,Mark Steven Johnson,276.0,115802596.0,Action|Fantasy|Thriller,Nicolas Cage,Ghost Rider,182661,681.0,English,110000000.0,2007.0,5.2,0,5802596.0,Action,Fantasy
243,John Woo,152.0,40911830.0,Action|Drama|War,Nicolas Cage,Windtalkers,55994,454.0,English,115000000.0,2002.0,6.0,0,-74088170.0,Action,Drama
282,Dominic Sena,175.0,101643008.0,Action|Crime|Thriller,Nicolas Cage,Gone in Sixty Seconds,218341,498.0,English,90000000.0,2000.0,6.5,0,11643008.0,Action,Crime
300,Jon Turteltaub,193.0,173005002.0,Action|Adventure|Comedy|Family|Mystery,Nicolas Cage,National Treasure,255447,692.0,English,100000000.0,2004.0,6.9,0,73005002.0,Action,Adventure
455,John Woo,155.0,112225777.0,Action|Crime|Sci-Fi|Thriller,Nicolas Cage,Face/Off,283967,535.0,English,80000000.0,1997.0,7.3,11000,32225777.0,Action,Crime
528,Michael Bay,122.0,134006721.0,Action|Adventure|Thriller,Nicolas Cage,The Rock,259492,415.0,English,75000000.0,1996.0,7.4,51000,59006721.0,Action,Adventure
565,Brian De Palma,117.0,55585389.0,Crime|Mystery|Thriller,Nicolas Cage,Snake Eyes,64121,241.0,English,69000000.0,1998.0,5.9,880,-13414611.0,Crime,Mystery
668,Oliver Stone,242.0,70236496.0,Drama|History|Thriller,Nicolas Cage,World Trade Center,67395,564.0,English,63000000.0,2006.0,6.0,0,7236496.0,Drama,History
696,David Bowers,138.0,19548064.0,Action|Animation|Comedy|Family|Sci-Fi,Nicolas Cage,Astro Boy,25681,77.0,English,65000000.0,2009.0,6.3,0,-45451936.0,Action,Animation
732,Brett Ratner,121.0,75764085.0,Comedy|Drama|Fantasy|Romance,Nicolas Cage,The Family Man,85844,322.0,English,60000000.0,2000.0,6.7,0,15764085.0,Comedy,Drama
831,Mark Neveldine,287.0,51774002.0,Action|Fantasy|Thriller,Nicolas Cage,Ghost Rider: Spirit of Vengeance,87745,331.0,English,57000000.0,2011.0,4.3,18000,-5225998.0,Action,Fantasy
854,Brad Silberling,110.0,78745923.0,Drama|Fantasy|Romance,Nicolas Cage,City of Angels,94407,322.0,English,55000000.0,1998.0,6.7,0,23745923.0,Drama,Fantasy
950,Alex Proyas,279.0,79948113.0,Drama|Mystery|Sci-Fi|Thriller,Nicolas Cage,Knowing,186879,791.0,English,50000000.0,2009.0,6.2,0,29948113.0,Drama,Mystery
1032,Patrick Lussier,296.0,10706786.0,Action|Fantasy|Thriller,Nicolas Cage,Drive Angry,81800,211.0,English,50000000.0,2011.0,5.5,15000,-39293214.0,Action,Fantasy
1051,Francis Ford Coppola,36.0,25900000.0,Crime|Drama|Music,Nicolas Cage,The Cotton Club,12771,84.0,English,58000000.0,1984.0,6.5,828,-32100000.0,Crime,Drama
1111,John A. Davis,105.0,28133159.0,Adventure|Animation|Comedy|Family|Fantasy,Nicolas Cage,The Ant Bully,30055,70.0,English,50000000.0,2006.0,5.9,593,-21866841.0,Adventure,Animation
1130,Danny Pang,125.0,15279680.0,Action|Crime|Thriller,Nicolas Cage,Bangkok Dangerous,48245,154.0,English,40000000.0,2008.0,5.4,0,-24720320.0,Action,Crime
1170,Andrew Niccol,168.0,24127895.0,Crime|Drama|Thriller,Nicolas Cage,Lord of War,248123,437.0,English,50000000.0,2005.0,7.6,10000,-25872105.0,Crime,Drama
1257,Joel Schumacher,138.0,36283504.0,Mystery|Thriller,Nicolas Cage,8MM,104564,587.0,English,40000000.0,1999.0,6.5,0,-3716496.0,Mystery,Thriller
1291,Barbet Schroeder,40.0,14942422.0,Action|Crime|Thriller,Nicolas Cage,Kiss of Death,14226,60.0,English,40000000.0,1995.0,5.9,555,-25057578.0,Action,Crime
1516,Simon West,98.0,183125.0,Action|Crime|Drama|Thriller,Nicolas Cage,Stolen,36914,86.0,English,35000000.0,2012.0,5.5,0,-34816875.0,Action,Crime
1562,Martin Scorsese,163.0,16640210.0,Drama|Thriller,Nicolas Cage,Bringing Out the Dead,53028,382.0,English,55000000.0,1999.0,6.8,0,-38359790.0,Drama,Thriller
2005,Werner Herzog,280.0,1697956.0,Crime|Drama,Nicolas Cage,Bad Lieutenant: Port of Call New Orleans,64944,212.0,English,20000000.0,2009.0,6.7,6000,-18302044.0,Crime,Drama
2278,Gore Verbinski,156.0,12469811.0,Comedy|Drama,Nicolas Cage,The Weather Man,69172,316.0,English,22000000.0,2005.0,6.6,0,-9530189.0,Comedy,Drama
2386,Spike Jonze,241.0,22245861.0,Comedy|Drama,Nicolas Cage,Adaptation.,143251,710.0,English,19000000.0,2002.0,7.7,0,3245861.0,Comedy,Drama
2399,Vic Armstrong,169.0,13998282.0,Action|Drama|Fantasy|Mystery|Thriller,Nicolas Cage,Left Behind,24854,374.0,English,16000000.0,2014.0,3.1,31000,-2001718.0,Action,Drama
2413,Francis Ford Coppola,44.0,41382841.0,Comedy|Drama|Fantasy|Romance,Nicolas Cage,Peggy Sue Got Married,27149,96.0,English,18000000.0,1986.0,6.3,0,23382841.0,Comedy,Drama
2568,Vic Armstrong,169.0,13998282.0,Action|Drama|Fantasy|Mystery|Thriller,Nicolas Cage,Left Behind,24854,374.0,English,16000000.0,2014.0,3.1,31000,-2001718.0,Action,Drama
3894,Mike Figgis,123.0,31968347.0,Drama|Romance,Nicolas Cage,Leaving Las Vegas,93894,286.0,English,3600000.0,1995.0,7.6,0,28368347.0,Drama,Romance
3938,David Gordon Green,232.0,371897.0,Drama,Nicolas Cage,Joe,36494,118.0,English,4000000.0,2013.0,6.9,11000,-3628103.0,Drama,None

In [21]:
# Write your code for combining the three dataframes here
c=pd.concat([Robert_De_Niro,Johnny_Depp,Nicolas_Cage], ignore_index=True)
c

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
0,Paul Weitz,180.0,148383780.0,Comedy|Romance,Robert De Niro,Little Fockers,85531,152.0,English,100000000.0,2010.0,5.5,0,48383780.0,Comedy,Romance
1,Des McAnuff,49.0,26000610.0,Adventure|Animation|Comedy|Family|Fantasy,Robert De Niro,The Adventures of Rocky & Bullwinkle,16611,197.0,English,76000000.0,2000.0,4.1,413,-49999390.0,Adventure,Animation
2,Bibo Bergeron,143.0,160762022.0,Adventure|Animation|Comedy|Family,Robert De Niro,Shark Tale,132415,288.0,English,75000000.0,2004.0,6.0,0,85762022.0,Adventure,Animation
3,Frank Oz,141.0,71069884.0,Crime|Drama|Thriller,Robert De Niro,The Score,101899,445.0,English,68000000.0,2001.0,6.8,0,3069884.0,Crime,Drama
4,Jay Roach,141.0,279167575.0,Comedy|Romance,Robert De Niro,Meet the Fockers,211296,428.0,English,80000000.0,2004.0,6.3,0,199167575.0,Comedy,Romance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Vic Armstrong,169.0,13998282.0,Action|Drama|Fantasy|Mystery|Thriller,Nicolas Cage,Left Behind,24854,374.0,English,16000000.0,2014.0,3.1,31000,-2001718.0,Action,Drama
108,Francis Ford Coppola,44.0,41382841.0,Comedy|Drama|Fantasy|Romance,Nicolas Cage,Peggy Sue Got Married,27149,96.0,English,18000000.0,1986.0,6.3,0,23382841.0,Comedy,Drama
109,Vic Armstrong,169.0,13998282.0,Action|Drama|Fantasy|Mystery|Thriller,Nicolas Cage,Left Behind,24854,374.0,English,16000000.0,2014.0,3.1,31000,-2001718.0,Action,Drama
110,Mike Figgis,123.0,31968347.0,Drama|Romance,Nicolas Cage,Leaving Las Vegas,93894,286.0,English,3600000.0,1995.0,7.6,0,28368347.0,Drama,Romance
111,David Gordon Green,232.0,371897.0,Drama,Nicolas Cage,Joe,36494,118.0,English,4000000.0,2013.0,6.9,11000,-3628103.0,Drama,None

In [22]:
c=c.groupby('actor_1_name').mean()
c.sort_values(by='num_critic_for_reviews', ascending=False)

,num_critic_for_reviews,gross,num_voted_users,num_user_for_reviews,budget,title_year,imdb_score,movie_facebook_likes,Profit
actor_1_name,,,,,,,,,
Johnny Depp,250.333333,9.525100e+07,200850.923077,580.230769,8.042564e+07,2003.384615,6.794872,16665.717949,1.482536e+07
Nicolas Cage,167.258065,4.782809e+07,100209.580645,345.741935,5.405161e+07,2003.354839,6.164516,6382.451613,-6.223520e+06
Robert De Niro,141.857143,5.001774e+07,135126.047619,297.095238,3.655952e+07,1999.166667,6.709524,6540.261905,1.345822e+07